apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
        tier: support-services
    spec:
      containers:
        - name: auth-server
          image: auth-server:0.0.1-SNAPSHOT
          ports:
            - containerPort: 9090
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app: auth-server
    tier: support-services
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: auth-server
    tier: support-services