apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
    tier: support-services
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: auth
    tier: support-services
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
        tier: support-services
    spec:
      containers:
      - name: auth
        image: fsdapps/auth-server:0.0.1-SNAPSHOT
        ports:
        - containerPort: 9090
        imagePullPolicy: IfNotPresent
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker