apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: config
    tier: support-services
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: config
    tier: support-services
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config
        tier: support-services
    spec:
      containers:
      - name: config
        image: fsdapps/config-server:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8888
        imagePullPolicy: IfNotPresent
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker