apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
        tier: support-services
    spec:
      containers:
        - name: discovery-server
          image: discovery-server:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8761
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  labels:
    app: discovery-server
    tier: support-services
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: discovery-server
    tier: support-services