apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app: discovery
    tier: support-services
spec:
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    app: discovery
    tier: support-services
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery
        tier: support-services
    spec:
      containers:
      - name: config
        image: fsdapps/discovery-server:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8761
        imagePullPolicy: IfNotPresent
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker