apiVersion: v1
kind: Service
metadata:
  name: edge
  labels:
    app: edge
    tier: support-services
spec:
  ports:
  - port: 8765
    targetPort: 8765
  selector:
    app: edge
    tier: support-services
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edge
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edge
        tier: support-services
    spec:
      containers:
      - name: edge
        image: fsdapps/edge-server:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8765
        imagePullPolicy: IfNotPresent
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker