server:
  port: 8765
  
info:
  component: Edge Server

hystrix:
  threadpool:
    default:
      # Maximum number of concurrent requests when using thread pools (Default: 10)
      coreSize: 100
      # Maximum LinkedBlockingQueue size - -1 for using SynchronousQueue (Default: -1)
      maxQueueSize: -1
      # Queue size rejection threshold (Default: 5)
      queueSizeRejectionThreshold: 5
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 3
      execution:
        isolation:
#          strategy: SEMAPHORE, no thread pool but timeout handling stops to work
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5

ribbon:
  ConnectTimeout: 100
  ReadTimeout: 70000

---
spring:
  profiles: local
  
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: development
logging:
  level:
    org.springframework.boot.context.embedded.tomcat: INFO  # Required for deploy script to be able to read port number from log file

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  #ignoredServices: "*"
  prefix: /api/v1
  routes:
    inventory-composite-service: /inventory-search/**
    carton-service:
      path: /carton-receiving/**
      sensitiveHeaders:
